import React from 'react'

const CoursesList = () => {
  return (
    <div>
      <h1>Course</h1>
      <h1>Learn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the bestLearn from the best </h1>
      <p>Discover our top-rated courses across various categories. From coding and design to Discover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design to</p>
      <p>Discover our top-rated courses across various categories. From coding and design to Discover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design toDiscover our top-rated courses across various categories. From coding and design to</p>
      <p>Discover our top-rated courses across various categories. From coding and design to</p>
      <p>Discover our top-rated courses across various categories. From coding and design to</p>
      <p>Discover our top-rated courses across various categories. From coding and design to</p>
      <p>Discover our top-rated courses across various categories. From coding and design to</p>
      <p>Discover our top-rated courses across various categories. From coding and design to</p>
      <p>Discover our top-rated courses across various categories. From coding and design to</p>
      <p>Discover our top-rated courses across various categories. From coding and design to</p>
    </div>
  )
}

export default CoursesList
